
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfnxkeofitssrbfyespu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbnhrZW9maXRzc3JiZnllc3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDA5NzUsImV4cCI6MjA2MzU3Njk3NX0.bFLkIZxWx_vmt8VHDhzmmPzmfgMy3dsYUXDUbKzk-zI";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
